
version: 2


source:
 - name: customers
   tables:
     - name: hevo_raw_customers
     - name: hevo_raw_orders
     - name: hevo_raw_payments



models:
 
  - name: customers
    description: "Customer table with orders and payment details for distinct users"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          -not_null
          -unique